const path = require("path");
const animFrames = [];
animFrames.push({type: 'distort', delay: 0, targetTime: 1000});
animFrames.push(new AnimImageFile(getAssetAbsPath("2_1.png"),
    100, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f1.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f4.jpg"),
    500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f6.jpg"),
    800, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f7.jpg"),
    1000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f8.jpg"),
    1000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f9.jpg"),
    1000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("jquery.jpg"),
    14000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("ember.jpg"),
    2000, 700));
animFrames.push(new AnimImageFile(getAssetAbsPath("grunt.jpg"),
    2000, 700));
animFrames.push(new AnimImageFile(getAssetAbsPath("bower.jpg"),
    2000, 700));
animFrames.push(new AnimImageFile(getAssetAbsPath("bootstrap.jpg"),
    2000, 700));
animFrames.push(new AnimImageFile(getAssetAbsPath("1.png"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("strictEquality.jpg"),
    6000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("varCollision.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("funcBinding.jpg"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("memoryLeak.jpg"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("consoleLog.jpg"),
    6000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_1.jpg"),
    6500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_2.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("fbdb.jpg"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_1.jpg"),
    4500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_2.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("web_mobile_pc.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f9.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("mocha.jpg"),
    12000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("lint.jpg"),
    2000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("webpack.jpg"),
    2000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("startups.jpg"),
    2000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("chell.jpg"),
    4000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("asyncawait.jpg"),
    6000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("lodash.jpg"),
    5000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("redux.jpg"),
    6000, 600));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_1.jpg"),
    7500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_2.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("xml.jpg"),
    1500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("json.jpg"),
    1500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_1.jpg"),
    4500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_2.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("web_mobile_pc.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f9.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("vue.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("d3.jpg"),
    2500, 500));
animFrames.push(new AnimImageFile(getAssetAbsPath("mongo.jpg"),
    2500, 500));
animFrames.push(new AnimImageFile(getAssetAbsPath("react.jpg"),
    2500, 500));
animFrames.push(new AnimImageFile(getAssetAbsPath("meteor.jpg"),
    2500, 500));
animFrames.push(new AnimImageFile(getAssetAbsPath("require.jpg"),
    2500, 500));
animFrames.push({type: 'distort', delay: 2500, targetTime: 1000});
animFrames.push(new AnimImageFile(getAssetAbsPath("livescript.jpg"),
    1500, 500));
animFrames.push(new AnimImageFile(getAssetAbsPath("chromium.jpg"),
    2500, 500));
animFrames.push(new AnimImageFile(getAssetAbsPath("class.jpg"),
    4500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("angular.jpg"),
    5000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("love_triangle.jpg"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("npm.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("love_java.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("addiction.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("sitchair1.jpg"),
    5000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("babel.jpg"),
    6000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("asyncloop.jpg"),
    6000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("typescript.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_love.jpg"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("ajax.jpg"),
    8500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("xss.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("prototype.jpg"),
    3000, 1000));
animFrames.push({type: 'distort', delay: 3000, targetTime: 1000});
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_1.jpg"),
    1000, 200));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_2.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("fbdb.jpg"),
    2000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_1.jpg"),
    4500, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("aynijs_2.jpg"),
    4000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("web_mobile_pc.jpg"),
    3000, 1000));
animFrames.push(new AnimImageFile(getAssetAbsPath("js_frames"+path.sep+"f9.jpg"),
    3000, 1000));
animFrames.push({type: 'distort', delay: 17000, targetTime: 1000});
animFrames.push({type: 'distort', delay: 30000, targetTime: 1000});

module.exports = animFrames;
